# Generated by Django 6.0 on 2025-12-23 08:57

from django.db import migrations, models

import gallery.utils


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_alter_screenshot_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screenshot",
            name="image",
            field=models.ImageField(upload_to=gallery.utils.get_file_path),
        ),
    ]
