# Generated by Django 6.0 on 2025-12-29 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_alter_screenshot_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_screenshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
